"""Question-level cache lookup tool for LangGraph Planner.

Enables reuse of previously solved and verified solutions across different papers
using composite SHA-256 signatures (text + marks + board + class_name).
"""

from typing import Any, Dict, Optional
from app.store.connection import get_db_session
from app.store.models import SolvedQuestionTable


def lookup_cached_question(
    signature: str,
    target_question_number: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Looks up a previously solved question by its composite signature.

    Args:
        signature: Composite SHA-256 signature generated by hash_utils.
        target_question_number: Optional question number in the current paper
            (e.g., '14' even if it was originally solved as '3').

    Returns:
        dict: SolutionContract adhering to Section 3 of the brief, or None.
    """
    if not signature:
        return None

    with get_db_session() as session:
        # Fetch the most confident verified answer with this signature
        cached_row = (
            session.query(SolvedQuestionTable)
            .filter(SolvedQuestionTable.question_signature == signature)
            .filter(SolvedQuestionTable.needs_teacher_check == False)  # Prefer verified answers
            .order_by(SolvedQuestionTable.confidence.desc(), SolvedQuestionTable.id.desc())
            .first()
        )

        # Fallback: if only rows with needs_teacher_check exist, grab the best one
        if not cached_row:
            cached_row = (
                session.query(SolvedQuestionTable)
                .filter(SolvedQuestionTable.question_signature == signature)
                .order_by(SolvedQuestionTable.confidence.desc(), SolvedQuestionTable.id.desc())
                .first()
            )

        if not cached_row:
            return None

        q_num = target_question_number if target_question_number is not None else cached_row.question_number

        return {
            "question_number": q_num,
            "answer": cached_row.answer,
            "steps": cached_row.steps or [],
            "mark_split": cached_row.mark_split or [],
            "common_mistakes": cached_row.common_mistakes or [],
            "confidence": float(cached_row.confidence or 0.95),
            "verified_by": f"cache:signature:{cached_row.verified_by or 'db'}",
            "needs_teacher_check": cached_row.needs_teacher_check,
        }
