"""Render the compiled LangGraph graphs (Mermaid) for docs and review.

    python -m app.workflow.visualize > docs/workflow_graph.md
"""
from __future__ import annotations

from app.workflow.deps import WorkflowDeps
from app.workflow.kb import InMemoryKnowledgeBase, InMemoryPaperRepository
from app.workflow.paper_graph import build_paper_graph
from app.workflow.question_graph import build_question_graph
from app.workflow.settings import WorkflowSettings


class _NoLLM:
    solver_model = verifier_model = "none"


def mermaid() -> str:
    deps = WorkflowDeps(kb=InMemoryKnowledgeBase(), papers=InMemoryPaperRepository(), llm=_NoLLM(), settings=WorkflowSettings())
    paper = build_paper_graph(deps).get_graph(xray=0).draw_mermaid()
    question = build_question_graph(deps).get_graph().draw_mermaid()
    return (
        "# Compiled graphs (generated by `python -m app.workflow.visualize`)\n\n"
        "## Paper graph\n\n```mermaid\n" + paper + "\n```\n\n"
        "## Per-question graph (the `question_pipeline` node)\n\n```mermaid\n" + question + "\n```\n"
    )


if __name__ == "__main__":
    print(mermaid())
